# Generated by Django 3.0.3 on 2020-07-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
